"""Dummy functions used by sample_tasks.py"""

import random
import time

from loguru import logger
from pyosotis.task import Task

# key constants for the shared dictionary
PROJECT_NAME = "project_name"
REPOSITORIES = "repositories"
USERNAME = "username"


def clone_main(task: Task, shared_dict: dict):
    """Simulates cloning the main repositories.

    Reads the project name generated by an earlier task from the ShareDict.
    Writes the list of cloned projects to shared_dict."""
    logger.info(
        (
            f"{task.title}: clone_main({shared_dict[PROJECT_NAME]}): "
            "Emulate cloning of main project repositories."
        )
    )

    repos = ["my_project_core", "my_project_gui"]
    for repo in repos:
        logger.info(f"clone_main: clone {repo}")
        time.sleep(3)

    shared_dict[REPOSITORIES] = repos

    logger.info("clone_main: done.")


def clone_auxillary(task: Task, shared_dict: dict):
    """Simulates cloning several auxillary repositories."""
    logger.info(
        (
            f"clone_auxillary({shared_dict[PROJECT_NAME]}): "
            "Emulate cloning of auxillary repositories."
        )
    )
    for i in range(5):
        logger.info(f"clone_remaining: clone helper {i + 1}")
        time.sleep(i + 1)
    logger.info("clone_remaining: done.")


def create_project_name(task: Task, shared_dict: dict):
    """Creates a custom name for the project and stores it in shared_dict."""

    logger.info("create_project_name: Please wait, this may take a while ...")
    time.sleep(4)

    colors = ("Red", "Green", "Blue", "Violet", "Black", "White")
    shapes = ("Circle", "Square", "Triangle", "Rectangle")

    project_name = random.choice(colors) + random.choice(shapes)
    if USERNAME in shared_dict:
        project_name += f" by {shared_dict[USERNAME]}"

    shared_dict[PROJECT_NAME] = project_name

    logger.info(
        f"create_project_name: The project is called {shared_dict[PROJECT_NAME]}"
    )

    return project_name


def build_binaries(task: Task, shared_dict: dict):
    """Simulates building the binaries from source.

    Reads the repository names from shared_dict."""

    logger.info(
        f"build_binaries: Building binaries for project {shared_dict[PROJECT_NAME]}"
    )
    for repo in shared_dict[REPOSITORIES]:
        logger.info(f"build_binaries: processing repository {repo}")
        time.sleep(random.random() * 4.0)

    logger.info("build_binaries: finished.")
